<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'slug' => 'frontend',
                'stack_id' => 'frontend',
                'title' => 'Frontend Engineering',
                'subtitle' => 'Master React, Next.js, and modern frontend frameworks',
                'description' => 'Build responsive, accessible, and performant web applications. This comprehensive course takes you from HTML/CSS fundamentals to building production-ready React and Next.js applications. You will learn component architecture, state management, routing, API integration, testing, and deployment.',
                'short_description' => 'Master React, Next.js, and modern frontend frameworks. Build responsive, accessible, and performant web applications.',
                'category' => 'Web Development',
                'icon' => '🖥',
                'thumbnail_url' => 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800',
                'cover_url' => 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=1600',
                'instructor_name' => 'John Doe',
                'instructor_title' => 'Senior Frontend Engineer',
                'instructor_bio' => '10+ years building web applications at scale. Previously at Google and Meta. Passionate about teaching and open source.',
                'instructor_experience' => 10,
                'instructor_students' => 2500,
                'instructor_courses' => 3,
                'instructor_rating' => 4.8,
                'duration' => '12 weeks',
                'skill_level' => 'Beginner to Advanced',
                'language' => 'English',
                'certificate_included' => true,
                'lifetime_access' => true,
                'mobile_access' => true,
                'downloadable_resources' => true,
                'projects_included' => true,
                'community_access' => true,
                'price_ngn' => 250000.00,
                'price_usd' => 1500.00,
                'original_price_ngn' => 300000.00,
                'original_price_usd' => 1800.00,
                'discount_percentage' => 17,
                'currency' => 'NGN',
                'is_free' => false,
                'is_published' => true,
                'average_rating' => 4.5,
                'total_reviews' => 128,
                'students_enrolled' => 2500,
                'what_you_learn' => [
                    'Build responsive layouts with HTML5, CSS3, and Tailwind CSS',
                    'Master JavaScript (ES6+) including async patterns and modules',
                    'Build component-driven UIs with React 19 and Server Components',
                    'Develop full-stack applications with Next.js App Router',
                    'Implement authentication, data fetching, and API routes',
                    'Write unit and integration tests with Vitest and Playwright',
                    'Deploy to Vercel with CI/CD and preview deployments',
                    'Optimize performance with Lighthouse, Core Web Vitals, and lazy loading',
                ],
                'includes' => [
                    'Lifetime access to all course materials',
                    'Downloadable exercise files and project templates',
                    'Access to private Discord community',
                    'Code reviews from industry mentors',
                    'Certificate of completion',
                    'Career coaching and resume review',
                    'Interview preparation material',
                    'Job placement assistance (Pro plan)',
                ],
                'requirements' => [
                    'Basic computer literacy',
                    'Familiarity with programming concepts is helpful but not required',
                    'A computer with internet connection',
                    'Willingness to learn and build',
                ],
                'metadata' => ['prerequisites' => ['Basic computer skills'], 'ideal_for' => ['Beginners', 'Career switchers', 'Self-taught developers']],
            ],
            [
                'slug' => 'backend',
                'stack_id' => 'backend',
                'title' => 'Backend Engineering',
                'subtitle' => 'Design scalable APIs, microservices, and serverless architectures',
                'description' => 'Master backend development with Node.js, Python, and Go. Learn to design and build RESTful APIs, GraphQL servers, microservices, and serverless functions. Covers databases, caching, message queues, authentication, and cloud deployment.',
                'short_description' => 'Design scalable APIs, microservices, and serverless architectures using Node.js, Python, and Go.',
                'category' => 'Backend Development',
                'icon' => '⚙',
                'thumbnail_url' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
                'cover_url' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1600',
                'instructor_name' => 'Jane Smith',
                'instructor_title' => 'Senior Backend Engineer',
                'instructor_bio' => 'Backend infrastructure expert with 12+ years experience. Built systems serving millions of users at Stripe and AWS.',
                'instructor_experience' => 12,
                'instructor_students' => 1800,
                'instructor_courses' => 5,
                'instructor_rating' => 4.7,
                'duration' => '14 weeks',
                'skill_level' => 'Intermediate to Advanced',
                'language' => 'English',
                'certificate_included' => true,
                'lifetime_access' => true,
                'mobile_access' => true,
                'downloadable_resources' => true,
                'projects_included' => true,
                'community_access' => true,
                'price_ngn' => 250000.00,
                'price_usd' => 1500.00,
                'original_price_ngn' => 300000.00,
                'original_price_usd' => 1800.00,
                'discount_percentage' => 17,
                'currency' => 'NGN',
                'is_free' => false,
                'is_published' => true,
                'average_rating' => 4.6,
                'total_reviews' => 96,
                'students_enrolled' => 1800,
                'what_you_learn' => [
                    'Build RESTful and GraphQL APIs with Node.js and Express',
                    'Design database schemas with PostgreSQL and Prisma ORM',
                    'Implement caching strategies with Redis',
                    'Build event-driven systems with message queues (RabbitMQ, Bull)',
                    'Containerize applications with Docker and Docker Compose',
                    'Deploy to AWS/GCP with CI/CD pipelines',
                    'Implement authentication and authorization (JWT, OAuth2)',
                    'Write automated tests and monitor production systems',
                ],
                'includes' => [
                    'Lifetime access to all course materials',
                    'Downloadable code repositories and Postman collections',
                    'Access to private Discord community',
                    'Code reviews from industry mentors',
                    'Certificate of completion',
                    'Career coaching and resume review',
                    'System design interview preparation',
                    'Job placement assistance (Pro plan)',
                ],
                'requirements' => [
                    'Basic programming knowledge (any language)',
                    'Familiarity with command line',
                    'Understanding of HTTP and web fundamentals',
                    'A computer with 8GB+ RAM recommended',
                ],
                'metadata' => ['prerequisites' => ['Basic programming knowledge'], 'ideal_for' => ['Junior developers', 'Full-stack developers', 'CS graduates']],
            ],
            [
                'slug' => 'fullstack',
                'stack_id' => 'fullstack',
                'title' => 'Full-Stack Development',
                'subtitle' => 'Become a complete developer from frontend to backend',
                'description' => 'The complete full-stack program covering both frontend and backend development. Build production-ready applications end-to-end with React, Next.js, Node.js, PostgreSQL, and modern DevOps practices. Perfect for those who want to be self-sufficient developers.',
                'short_description' => 'Become a complete developer. Master both frontend and backend to build production-ready applications end-to-end.',
                'category' => 'Full-Stack Development',
                'icon' => '🚀',
                'thumbnail_url' => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
                'cover_url' => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1600',
                'instructor_name' => 'Mike Johnson',
                'instructor_title' => 'Full-Stack Architect',
                'instructor_bio' => 'Full-stack engineer turned tech lead. Built and scaled products at Airbnb and Shopify. Mentored 100+ engineers.',
                'instructor_experience' => 14,
                'instructor_students' => 3200,
                'instructor_courses' => 8,
                'instructor_rating' => 4.9,
                'duration' => '20 weeks',
                'skill_level' => 'All Levels',
                'language' => 'English',
                'certificate_included' => true,
                'lifetime_access' => true,
                'mobile_access' => true,
                'downloadable_resources' => true,
                'projects_included' => true,
                'community_access' => true,
                'price_ngn' => 350000.00,
                'price_usd' => 2000.00,
                'original_price_ngn' => 450000.00,
                'original_price_usd' => 2500.00,
                'discount_percentage' => 22,
                'currency' => 'NGN',
                'is_free' => false,
                'is_published' => true,
                'average_rating' => 4.8,
                'total_reviews' => 215,
                'students_enrolled' => 3200,
                'what_you_learn' => [
                    'Build complete web applications from scratch',
                    'Master React, Next.js, and TypeScript for the frontend',
                    'Build robust APIs with Node.js, Express, and Prisma',
                    'Design and optimize PostgreSQL databases',
                    'Implement authentication, payments, and file uploads',
                    'Add real-time features with WebSockets',
                    'Write unit, integration, and E2E tests',
                    'Deploy full-stack apps with Docker and CI/CD',
                    'Monitor, debug, and optimize production applications',
                    'Lead technical projects and mentor junior developers',
                ],
                'includes' => [
                    'Lifetime access to all course materials',
                    'Downloadable full-stack starter templates',
                    'Access to private Discord community',
                    'Code reviews from industry mentors',
                    'Certificate of completion',
                    'Career coaching and resume review',
                    'System design and technical interview prep',
                    'Job placement assistance (Pro plan)',
                    'Portfolio project with code review',
                    'LinkedIn optimization workshop',
                ],
                'requirements' => [
                    'Basic understanding of how websites work',
                    'Some programming experience is helpful but not required',
                    'A computer with 8GB+ RAM',
                    'Commitment to 10-15 hours per week',
                ],
                'metadata' => ['prerequisites' => ['Basic computer skills', 'Some programming experience helpful'], 'ideal_for' => ['Career changers', 'Entrepreneurs', 'Aspiring tech leads']],
            ],
            [
                'slug' => 'mobile',
                'stack_id' => 'mobile',
                'title' => 'Mobile Development',
                'subtitle' => 'Build cross-platform mobile apps with React Native and Flutter',
                'description' => 'Learn to build beautiful, performant mobile applications for both iOS and Android. Master React Native and Flutter frameworks, state management, native modules, app store deployment, and push notifications.',
                'short_description' => 'Build cross-platform mobile apps with React Native and Flutter. Deploy to both iOS and Android stores.',
                'category' => 'Mobile Development',
                'icon' => '📱',
                'thumbnail_url' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
                'cover_url' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1600',
                'instructor_name' => 'Sarah Williams',
                'instructor_title' => 'Mobile Tech Lead',
                'instructor_bio' => 'Mobile development expert with 8+ years in React Native and Flutter. Apps built have 10M+ combined downloads on App Store and Google Play.',
                'instructor_experience' => 8,
                'instructor_students' => 1200,
                'instructor_courses' => 2,
                'instructor_rating' => 4.6,
                'duration' => '14 weeks',
                'skill_level' => 'Intermediate',
                'language' => 'English',
                'certificate_included' => true,
                'lifetime_access' => true,
                'mobile_access' => true,
                'downloadable_resources' => true,
                'projects_included' => true,
                'community_access' => true,
                'price_ngn' => 250000.00,
                'price_usd' => 1500.00,
                'original_price_ngn' => 300000.00,
                'original_price_usd' => 1800.00,
                'discount_percentage' => 17,
                'currency' => 'NGN',
                'is_free' => false,
                'is_published' => true,
                'average_rating' => 4.4,
                'total_reviews' => 78,
                'students_enrolled' => 1200,
                'what_you_learn' => [
                    'Build cross-platform apps with React Native and Expo',
                    'Master Flutter and Dart for iOS and Android',
                    'Implement state management with Redux Toolkit and Riverpod',
                    'Integrate native device features (camera, GPS, biometrics)',
                    'Add push notifications with Firebase Cloud Messaging',
                    'Deploy to Apple App Store and Google Play Store',
                    'Implement offline support and data sync',
                    'Optimize performance for mobile devices',
                ],
                'includes' => [
                    'Lifetime access to all course materials',
                    'Downloadable project templates for React Native and Flutter',
                    'Access to private Discord community',
                    'Code reviews from industry mentors',
                    'Certificate of completion',
                    'App store submission checklist and guide',
                    'Portfolio building assistance',
                    'Job placement assistance (Pro plan)',
                ],
                'requirements' => [
                    'Basic programming knowledge (JavaScript or Python)',
                    'Understanding of React concepts is helpful',
                    'A computer with 16GB+ RAM recommended',
                    'An iOS or Android device for testing (emulator works too)',
                ],
                'metadata' => ['prerequisites' => ['Basic programming knowledge'], 'ideal_for' => ['Web developers going mobile', 'Aspiring mobile devs', 'Entrepreneurs']],
            ],
            [
                'slug' => 'ai',
                'stack_id' => 'ai',
                'title' => 'AI Engineering',
                'subtitle' => 'Dive into machine learning, LLMs, and AI-powered applications',
                'description' => 'Explore the cutting edge of AI engineering. Master machine learning fundamentals, deep learning, large language models (LLMs), RAG systems, AI agents, and MLOps. Build intelligent applications that solve real problems.',
                'short_description' => 'Dive into machine learning, LLMs, and AI-powered applications. Build intelligent systems that solve real problems.',
                'category' => 'AI / Machine Learning',
                'icon' => '🤖',
                'thumbnail_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
                'cover_url' => 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1600',
                'instructor_name' => 'Dr. Alex Chen',
                'instructor_title' => 'AI Research Scientist',
                'instructor_bio' => 'PhD in Machine Learning from MIT. Former research scientist at DeepMind. Published 20+ papers in top ML conferences.',
                'instructor_experience' => 15,
                'instructor_students' => 1500,
                'instructor_courses' => 4,
                'instructor_rating' => 4.9,
                'duration' => '16 weeks',
                'skill_level' => 'Advanced',
                'language' => 'English',
                'certificate_included' => true,
                'lifetime_access' => true,
                'mobile_access' => true,
                'downloadable_resources' => true,
                'projects_included' => true,
                'community_access' => true,
                'price_ngn' => 300000.00,
                'price_usd' => 1800.00,
                'original_price_ngn' => 380000.00,
                'original_price_usd' => 2200.00,
                'discount_percentage' => 21,
                'currency' => 'NGN',
                'is_free' => false,
                'is_published' => true,
                'average_rating' => 4.7,
                'total_reviews' => 54,
                'students_enrolled' => 1500,
                'what_you_learn' => [
                    'Master Python for data science and machine learning',
                    'Build and train neural networks with PyTorch and TensorFlow',
                    'Understand transformer architecture and attention mechanisms',
                    'Fine-tune LLMs using LoRA and QLoRA',
                    'Build RAG systems with LangChain and vector databases',
                    'Create AI agents and multi-agent systems',
                    'Deploy ML models to production with MLflow and Docker',
                    'Monitor and evaluate model performance in production',
                    'Implement MLOps pipelines and CI/CD for ML',
                    'Build end-to-end AI applications',
                ],
                'includes' => [
                    'Lifetime access to all course materials',
                    'Downloadable Jupyter notebooks and datasets',
                    'Access to private Discord community',
                    'Code reviews from industry mentors',
                    'Certificate of completion',
                    'Research paper reading group access',
                    'Kaggle competition mentorship',
                    'Job placement assistance (Pro plan)',
                    'GPU compute credits',
                    'Career coaching for AI roles',
                ],
                'requirements' => [
                    'Strong programming skills in Python',
                    'Understanding of linear algebra and statistics',
                    'Basic understanding of calculus',
                    'A computer with 16GB+ RAM (GPU recommended)',
                    'Willingness to read research papers',
                ],
                'metadata' => ['prerequisites' => ['Strong Python skills', 'Basic math (linear algebra, statistics)'], 'ideal_for' => ['Software engineers', 'Data scientists', 'Researchers']],
            ],
        ];

        foreach ($courses as $data) {
            Course::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
